### ISSUE TITLE
twitter duplicate news flash

### ISSUE THREAD

**Issue by Mano3** [hasadna/anyway#1094]
![Screenshot_1](https://user-images.githubusercontent.com/33526700/73541356-e0e33500-443a-11ea-8050-7b3045239de6.jpg)
A lot of duplicates news flash from twitter, need to investigate why it happens,
could it happen on other news sources?
Also, obviously need to remove the duplicated.
Another thing to note, is that the location of the accident was actually in the second sentence of the tweet, so the location extractor didn't even look at it (since it takes into account only the first sentence, biased on ynet data)

**Must be taken care of ASAP.**

**Comment by Mano3** [comment]
@sagivharel -> could you take care of it? I prioritize this over the tags handling, but that's up to Atalya as well. 
@atalyaalon -> tagging you for reference

**Comment by Mano3** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/33526700/73541587-826a8680-443b-11ea-84c7-2b6ac5e5ffad.jpg)
Seems to happen also on ynet

**Comment by sagivharel** [comment]
its seems that there is one specific tweet which got crazy and was added numerous times.
After a brief look at the code i couldn't find a specific issue that could relate to the problem, also the inconsistency of the duplicated tweets and their timing make me think the problem is somehow related to the cron scheduling.

I'm having trouble building the local development environment so I cant debug the cron tasks, but maybe we should start by deleting all the duplicated rows from the tables and starting to inspect the duplication event from now on?
@Mano3 @atalyaalon what do you think? It's pretty hard to retro investigate those event

**Comment by atalyaalon** [comment]
@Mano3 @sagivharel I agree - let's not investigate now.
@Mano3 please write a command to delete duplicates. I will make sure cron runs in a lower frequency (say once in 5 or 10 minutes) - my guess is that the current frequency is too high so we get dups.

**Comment by atalyaalon** [comment]
If this continues, then we'll investigate

**Comment by Mano3** [comment]
Also considering duplicates when querying the DB in the backend might be appropriate

**Comment by Mano3** [comment]
#1096 supposed to solve this
