### ISSUE TITLE
EURO DEMO accidents on road 20 by speed limit (excluding junctions)

### ISSUE THREAD

**Issue by ChayneAzriel** [hasadna/anyway#1505]
**Name**
Accidents count on road 20 by speed limit (excluding junctions)

**Title**
accidents on road 20 by speed limit

**Visualization**
![speed_limit_by_acci_type_road_20_2](https://user-images.githubusercontent.com/61120310/98536323-4a2c8a00-2290-11eb-8d5c-012a680f6979.png)

**Methodology**
count of accidents types on the road by the allowed speed limit where the accidents took place, starts with the highest

**Use case**
accident that is on the top 6 accidents types count on inter urban road X 

**SQL query**
[query on redash](https://app.redash.io/hasadna/queries/509330)

modified parameters:
road1
 language specific fields:
speed_limit

**Additional context**
representing only top counts of each accident type, other types are combined under 'other'

**Comment by atalyaalon** [comment]
@ChayneAzriel looks great!
Since there are many categories, I suggest we either:
1. Group categories - hence we'll have less categories
2. Show only the top 5 categories (for example by summing all of the accidents count)

@galraij any thoughts?

**Comment by MichalOren** [comment]
Looks GOOD (:
1. Can we switch axis? because Accident Type names will be easier to read when they are on left side of the table
2. I think it is better to show only the top 5 categories  (rather than group categories together)
3. color issue: value “1 accident” for example,  display with different color of intensity where i think it should display in same manner.

**Comment by ziv17** [comment]
What is the actual task?

**Comment by atalyaalon** [comment]
@ziv17 we need to improve this and other issue together with the data team - we'll discuss it in the coming meeting.

**Comment by ziv17** [comment]
> 
> 
> @ziv17 we need to improve this and other issue together with the data team - we'll discuss it in the coming meeting.

We did not get to it in the meeting today. When do you want to discuss it?

**Comment by atalyaalon** [comment]
@ziv17 I opened https://github.com/hasadna/anyway/issues/1543 - once we decide on a clear workflow with the data team - it will be easier for them and for us - they will modify the description and we'll move on from there

**Comment by atalyaalon** [comment]
@MichalOren @ChayneAzriel 
I suggest rethinking of this infographics - since right now I think it can be confusing.
Perhaps create a view/heat map of speed limit and severity, or maybe focus only on the percentage of both fatal and severe accidents out of the total accidents in this speed.

@galraij @MichalOren  I would design here infographics in the shape of a car speed meter - in this way we'll be able to use a range (sum accidents from different speeds together).

Also wondering how much this data is reliable? @MichalOren @ChayneAzriel how many nulls do we have in the data? Can we trust this column?

**Comment by ChayneAzriel** [comment]
most of the accidents on this column are unknown, I think that as long as we don't know what length each speed limit part of the road is it's hard to understand what is the meaning of the numbers

**Comment by ChayneAzriel** [comment]
following our conversation, in the meantime we will not be using this infographic

**Comment by atalyaalon** [comment]
@ChayneAzriel thank you, closing this issue.
