### ISSUE TITLE
EURO DEMO Support localization

### ISSUE THREAD

**Issue by ziv17** [hasadna/anyway#1559]
To support languages we will:

- Add a parameter `lang` to infographics api. 
- Currently we will support two languages: `en`, `he`. If not supplied, default is `he`.
- Update the infographics generating functions (up to RequestParams) to accept the new parameter
- Update the cache generation to store in cache both languages.

**Comment by c881** [comment]
I guess "infographics_dictionaries.py" should contain values for both languages.

**Comment by atalyaalon** [comment]
@ziv17 please add this parameter to query (Any localized text is already handled using the lang param)
If it's not difficult - let's perform localization after cache extraction - for that I think that perhaps we should add per widget the localized fields (not all needs to be localized, some are numbers for example).
What do you think?

**Comment by ziv17** [comment]
A few questions:

1. How will the `lang` parameter value reach the code the performs the choosing of the correct text?
2. What is the language that is currently produced?
3. Is currently all localization implemented with same mechanism?
4. Is all needed localization already implemented?

**Comment by atalyaalon** [comment]
1. Lang parameter will be passed in query by FE - see [following code](https://github.com/hasadna/anyway/blob/a3bec547bdecaba816a464f6b7e7ab554826ab4b/anyway/flask_app.py#L316) handling it for the bable localizer and[ the following code using the lang param](https://github.com/hasadna/anyway/blob/8271b7297f872f3829632150c854936c0351227d/anyway/localization.py#L217)
2. @idosavion is there a default language? not sure what's in the [app.config["LANGUAGES"]](https://github.com/hasadna/anyway/blob/a3bec547bdecaba816a464f6b7e7ab554826ab4b/anyway/flask_app.py#L318)
3. We just started - but yes - that's the goal - [see an examle pr](https://github.com/hasadna/anyway/pull/1590/files)
4. No - we just started - that's why that's a good point to stop and think what's best.

**Comment by atalyaalon** [comment]
Also - it made me think - when we add a new news flash and calculate the Widgets data for this news flash - what's the language is used? Since this is not a request coming from the API, will it be just a default language?

**Comment by ziv17** [comment]
If we do localization after the cache, then we generate the result of the widget in two stages. First, without a language. We just prepare the input for the localization, and the data that is not changed by localization. In the second stage, we generate the localized text to the result.

**Comment by idosavion** [comment]
1. Current supported languages are `LANGUAGES = {"en": "English", "he": "עברית"}` - from `config.py`
2. I don't think we explicitly declaring a default language, this can be changed by providing a second parameter to `best_match` in localeselector.

**Comment by ziv17** [comment]
In my recent PR, I set `'he'` as default in the `infographics-data` api (in case `lang` parameter is not specified).
