### ISSUE TITLE
Widget: EURO DEMO Front to side accidents by severity on road 25

### ISSUE THREAD

**Issue by ChayneAzriel** [hasadna/anyway#1612]
**Name**
front_ to_side_ accidents_by_severity

**Title**
front to side accidents take a major part in more severe accidents

**Visualization**
<img width="870" alt="כרטיסיות_למוקאפ_דוח_עיתונאים_key" src="https://user-images.githubusercontent.com/3368312/101294133-1193b800-381e-11eb-871c-f2ef9ace5f2d.png">
**Visualization explanation**
accidents on road X, presented by accident severity, front to side accident type tend to be a severe one.

**Use case**
front to side accident on road X
when the percentage of front to side accidents in the given location and time frame is greater than 1.1 times the percentage of the front to side accidents in all of the roads

**SQL query**
[query on redash](https://app.redash.io/hasadna/queries/587505/source?p_Road%20SEGMENT%20ID=250020&p_Road%20segment%20id=250020)
modified parameters:
road_segment_id

**Additional context**

**Comment by galraij** [comment]
<img width="870" alt="כרטיסיות_למוקאפ_דוח_עיתונאים_key" src="https://user-images.githubusercontent.com/3368312/101294133-1193b800-381e-11eb-871c-f2ef9ace5f2d.png">

**Comment by atalyaalon** [comment]
@ChayneAzriel looks great! It's a very good insight! Wonderful work!

A few questions - regarding the redash query:
1. Regarding the Redash query - why is "road_object" there?
<img width="513" alt="Screen Shot 2020-12-06 at 23 30 57" src="https://user-images.githubusercontent.com/20992625/101293001-9e894200-381b-11eb-918d-bffa649fb70a.png">
2. Why are you using involved_markers_hebrew and not markers_hebrew?
3. Seems like the severe accidents numbers in query result do not match the graph's data - why is that?
4. Why did you add one_lane is not null?

**Comment by atalyaalon** [comment]
Also - @galraij created a cool visualization - perhaps it's better to add only fatal and severe accidents (it's better to use the word severe and not harsh)

**Comment by ChayneAzriel** [comment]
1. I think it's just left over from when I was playing with the data..
2. that's what I usually do, I reduce to the amount of accidents from the amount of  involves with distinct
3.the graph was created by python, there are little differences between the redash results and the python ones
4. at first I thought this road had parts that are defined as one lane, and it was part of trying to get the most accurate data.. but it's not true and I think we can ignore it 

I fixed the query according to your comments, there's a little change in the numbers. thank you..

great visualization! I do think that showing the minor accidents gives the full picture, and emphasize the major part that front to side accidents type take in severe and fatal accidents. if we are trying to attract the eye to the fatal and severe, maybe we can play with the colors (make the minor with same colors but more pastel)

**Comment by atalyaalon** [comment]
@ChayneAzriel Thanks!

1. great!
2. Instead, I suggest using the markers table or the markers_hebrew table
3. You can use the field accident_severity_hebrew for the translation instead of translating in the query itself.
However, we do prefer filtering by the code (accident_type = 2) - since the BackEnd team will implement it using the code.
4. You can also attach a Python code instead of the query.
5. Regarding minor (light) accidents - we prefer to focus on severe and fatal accidents - since light accidents can add a lot of noise.
6. Regarding the visualization - 

I wrote a shorter query - the shorter the query / the python code - it will be easier for the backend developers to understand and implement - [what do you think on this one?](https://app.redash.io/hasadna/queries/587505/source?p_Road%20SEGMENT%20ID=250020&p_Road%20segment%20id=250020)

**Comment by MichalOren** [comment]
Hi
I try to create a comprehensive over view:
widget name: front_ to_side_ accidents_by_severity 
visualization
![image](https://user-images.githubusercontent.com/61007501/183021440-becb01fa-eae6-4f1b-95f3-2ed4043c6fdb.png)

Update link to redash [query](https://redash.hasadna.org.il/queries/1066/source?p_Road%20SEGMENT%20ID=250020#1066
)
I think calculation of % need to happened on BE side and be a part of the json. That is to make FE implementation easer
 
Information text: 
תאונות קטלניות וקשות מסוג חזית-צד בהשוואה לסוגי תאונות אחרות באותו מקטע דרך 

if any other aspects are missing, please let me know

**Comment by BarVolunteering** [comment]
@MichalOren Are the query need to be time limit (e.g. 5 years back)?

**Comment by MichalOren** [comment]
Hi @BarVolunteering 
1. Usually we use 1, 3, 5 & 8 years, as time periods for our widgets. Do we need to change the query to support all ranges? 
2. You're right.  "all_roads_accidents" tag, looks unnecessary. 
TNX for your inputs

**Comment by BarVolunteering** [comment]
Changes will be done as part of PR:
https://github.com/hasadna/anyway/pull/2279

**Comment by MichalOren** [comment]
Hi @BarVolunteering
In order to clarify, I am adding the summary of the discussion with Bar and Daniel:
First, the Backend always transfers basic values, when the infographic needs to display a value in percentages %, it will happen in the Frontend.
Secondly, regarding the structure of the JSON, when there is no data regarding fatal or serious accidents, the JSON will only contain existing information. The same goes for the display, even partial information is displayed.

**Comment by BarVolunteering** [comment]
@MichalOren This is ready in PR:
https://github.com/hasadna/anyway/pull/2292

**Comment by BarVolunteering** [comment]
Done
