### ISSUE TITLE
Localize Widget - accident_count_by_car_type

### ISSUE THREAD

**Issue by atalyaalon** [hasadna/anyway#1691]
**Widget ID**
accident_count_by_car_type

**Widget Fields**
"car_type" (in "items")

**Dictionaries Missing**
Dictionaries to create (For example - Accident Severity Dictionary)
Note: Create a dictionary containing using the DB code as a key and not the Hebrew translation (for example `{1: 'fatal'}` rather than `{'קטלנית': 'fatal'}`)

**Widget Title**
"השוואת אחוז הרכבים בתאונות במקטע _______ לעומת ממוצע ארצי"

**Additional context**
- Existing translation to CBS fields - [see here](https://docs.google.com/spreadsheets/d/1gjeMsPEWayMZ4Z0tGDKkL0mDsXgIRQ4-aAadRpEP9Oc/edit?usp=sharing)
- Existing CBS Fields - [see here](https://docs.google.com/spreadsheets/d/1qaVV7NKXVYNmnxKZ4he2MKZDAjWPHiHfq-U5dcNZM5k/edit?usp=sharing)
(Note - if translation in file is not adequate - please create a better translation)

**Flask Babel**
For updating messages.pot with all strings for translation - use the following command: `pybabel extract -F babel.cfg -o messages.pot .`
For updating existing po files with new strings: `pybabel update -i messages.pot -d translations`

**Comment by ziv17** [comment]
Hi,
- I understand car type and vehicle type are synonyms. Do we want to change the widget name to use vehicle instead of car?
- Vehicle type constants appear both in `constants.py` and `backend_constants.py`. I am planning to change the representation of vehicle types to ease the management of the different vehicle categorizations and category names. I will do it only in `backend_constants`. Python code does not use vehicle constants from `constants.py`.

**Comment by ziv17** [comment]
Hi,
- I understand car type and vehicle type are synonyms. Do we want to change the widget name to use vehicle instead of car?
- Vehicle type constants appear both in `constants.py` and `backend_constants.py`. I am planning to change the representation of vehicle types to ease the management of the different vehicle categorizations and category names. I will do it only in `backend_constants`. Python code does not use vehicle constants from `constants.py`.

**Comment by ziv17** [comment]
Hi @atalyaalon , there are entries with blank vehicle type, should they be counted with `other` vehicle type, or as `unknown`?
