### ISSUE TITLE
Fix retina resolution icons

### ISSUE THREAD

**Issue by Bren** [hasadna/anyway#180]
Currently the icons aren't shown in their retina version.
The retina resolution icons (they have an '@2x' appendix to their name) need to be added.

Here is a link to the files: https://drive.google.com/file/d/0B6ImQhe4L0zMdlp2WnFqRTFLRHM/view?usp=sharing

**Comment by danielhers** [comment]
The retina icons are too big. Should I just scale them to half their size?
![screenshot from 2015-02-21 16 21 45](https://cloud.githubusercontent.com/assets/263363/6314403/e11b1edc-b9e5-11e4-90e1-504f3347d784.png)

**Comment by galraij** [comment]
I guess... but maybe @brendror knows...

**Comment by Bren** [comment]
The retina icons should only be displayed on high-res screens (such as mac retinas).
On regular screens the non-retina icons should be displayed.
I think there's a lot of info online on how to work with retina/non-retina images.

**Comment by danielhers** [comment]
Should not be difficult if you know what you're doing. Anyone?

**Comment by omerxx** [comment]
@OmerSchechter  your script worked.. it looks for the correct ones. should just add `icon` to the path:
`.../img/icons/`
![image](https://cloud.githubusercontent.com/assets/12237955/7802703/4182ba30-0344-11e5-9c24-c1d74dcffb65.png)

**Comment by OmerSchechter** [comment]
You are right, the script does work, but if you look closely you can see that it looks for the 'wrong' ones(i.e. not the marker icons that we have a retina version for, but other images on the page).
And there's no option to add the `/icons/`.

@danielhers I've managed to get the script 'working', so to speak.
The problem is, if our goal is to get the marker icons to switch to the retina version, the script doesn't do that. The script essentially works with `document.getElementsByTagName('img')` which finds all the 'img's on the page except for the googlemaps' icons.
I've looked at the "retina.js" code and it's not quite simple changing it to work with the marker icons as well.

What do you think about this solution?
I'm detecting Retina displays with a javascript script, and using RegEx to add the `@2x` prefix to the relevant images.
This solves the problem of the googlemaps icons, plus it won't double-load the images in case of a retina display(as I suspect "retina.js" will do), and the the urls are not hard coded.

```javascript
var isRetina = (
    window.devicePixelRatio > 1 ||
    (window.matchMedia && window.matchMedia("(-webkit-min-device-pixel-ratio: 1.5),(-moz-min-device-pixel-ratio: 1.5),(min-device-pixel-ratio: 1.5)").matches)
);

if(isRetina){
    function addRetinaPrefix(url){
        return url.replace(/(^.*)(\.png)$/gi,function switchFunction(x,y1,y2){return y1+"@2x"+y2;});
    }

    for (var icon in ICONS){
        for (var i in ICONS[icon]){            
            ICONS[icon][i] = addRetinaPrefix(ICONS[icon][i]);
        }
    }
    for (var icon in MULTIPLE_ICONS){
        MULTIPLE_ICONS[icon] = addRetinaPrefix(MULTIPLE_ICONS[icon]);
    }
    USER_LOCATION_ICON = addRetinaPrefix(USER_LOCATION_ICON);
    DISCUSSION_ICON = addRetinaPrefix(DISCUSSION_ICON);
}
```

**Comment by danielhers** [comment]
Done?

**Comment by OmerSchechter** [comment]
Done.
