### ISSUE TITLE
Replace cluster icons with new ones

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#181]
link to the new cluster icons:

Regular: https://drive.google.com/file/d/0B6ImQhe4L0zMTkM0YndXMTlxaVk/view?usp=sharing
Retina: https://drive.google.com/file/d/0B6ImQhe4L0zMNTVsVXlINjlZdzQ/view?usp=sharing

![cluster_1 2x](https://cloud.githubusercontent.com/assets/3368312/6314357/853ad02c-b9e4-11e4-8341-5149d6b35280.png)
![cluster_2 2x](https://cloud.githubusercontent.com/assets/3368312/6314359/8568c018-b9e4-11e4-9fbc-7d0ff5899d66.png)
![cluster_3 2x](https://cloud.githubusercontent.com/assets/3368312/6314358/8568859e-b9e4-11e4-97d4-28e45dac3166.png)
![cluster_4 2x](https://cloud.githubusercontent.com/assets/3368312/6314360/8573a014-b9e4-11e4-94dd-5d0c8de63375.png)

**Comment by OmerSchechter** [comment]
Quick question: why are there 4 different cluster icons here, whereas the map only has 3 different ones?(blue, yellow and red)
Am I missing something?

**Comment by danielhers** [comment]
There's also purple. Try zooming out to the whole country and waiting a bit
:)

**Comment by OmerSchechter** [comment]
I'm afraid to say that for me, zooming out to "zoom=11" and further out, there are no cluster icons showing(plus, no marker icons as well, of course).
In the console, I get:
```
GET http://www.anyway.co.il/markers?ne_lat=32.32808429548903&ne_lng=35.20423553…_date=1388527200&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0 net::ERR_INCOMPLETE_CHUNKED_ENCODING
```

Zoom 12 and further in seems to work fine(clusters are showing perfectly).

I guess I'll just take your word for it and work with the fourth icon as well.
But I think we should take a look at it, because the map is just empty and it is confusing.
Tested on Chrome.

**Comment by danielhers** [comment]
Right... looks like it times out after 30s. Will you open a separate issue
please?
