### ISSUE TITLE
Server-side clustering

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#190]

**Comment by danielhers** [comment]
In cluster mode, it's better to do the clustering on the server side and send just several points to the client rather than sending thousands of points when the client only needs to show a few.
Clustering is now done client-side using MarkerClusterer.

**Comment by njenia** [comment]
At first I thought about pre-indexing the data and persisting it to the db (since data is static). But after some thought I realized it's problematic because there is also a time and severity factor.
So there has to be a computation per-request on the server.
Right now the best think I can come up with is pre-indexing all accidents on the db and when a request comes in - get all points within view-able rectangle -> filter by date and severity -> calculate clusters.
Tell me if you have any more ideas.

**Comment by danielhers** [comment]
This seems like the best option we have... it's just the implementation
that's not trivial.

**Comment by samuelregev** [comment]
The problem with that is the high load on the server, it still required going through tens of thousands of records.

I have an idea that might do the trick:
Instead of letting the user to choose a various date range we only give them the option to choose a year range(2010-2013  for example).

this way we can do a pre count the number of accidents for every year ,every parameter(there only three parameters x2 - accurate and inaccurate), and every zoom level from 15 to 7.
Then we can save in a different tables the pre-count number.
This will required doing high load calculation only once, after that it will only require simple query to get this records.

@galraij what do you say, is it really that important to have this date range or maybe year range is enough?

**Comment by galraij** [comment]
If it is a big time/money saver year range is enough. Is it possible to leave that option for people who looking for something very specific and willing to wait?

Also- Is it possible that when a user choose 2012 it enables that year and another click disable? in this way people can just click 2011, 2005, 2003 and see all of it at the same time.

**Comment by njenia** [comment]
@samuelregev pre-calculation is an option I considered but it seems like it will take up lots of storage space. Maybe i'm wrong - if you can please check.

In the last session I finished implementing server-side clustering and there is a significant performance boost. For large zoom levels it's actually 2x faster, and on even larger zoom levels current production version doesn't show a thing (bug..), and the new solution finishes and works..

The bad news are that the latency is unacceptable - for large zoom levels it takes about 10-20 seconds.
I will try to make the calculation parallel and see if it gets better.
Does someone knows how much cores does the server have?

**Comment by danielhers** [comment]
It's a standard 1x Heroku dyno. Not sure how many cores they have.
Perhaps we can cache the clustering results to avoid doing the calculation
every time?
