### ISSUE TITLE
Add smart banner to promote android app

### ISSUE THREAD

**Issue by samuelregev** [hasadna/anyway#286]
See more details below
http://www.adianteapps.com/blog/article/smart-app-banners-promote-your-app-in-web

Our android app package name is il.co.anyway.app

**Comment by OmerSchechter** [comment]
Hey,
So I started working on it, and I have a quick question: why is `.navbar-fixed-top` positioned `fixed`? besides living up to it's name?;)
Would it be a problem having it positioned `absolute`?
I'm asking because obviously it causes problems when we want to have another element above it(i.e. the banner)
And it's not the first time it gave me problems.

**Comment by danielhers** [comment]
@OmerSchechter is this done? Where do I see the smart banner?

**Comment by samuelregev** [comment]
browse to http://anyway-unstable.herokuapp.com/ from your android device.

**Comment by danielhers** [comment]
Nice!
