### ISSUE TITLE
New pop-up window visual design

### ISSUE THREAD

**Issue by galraij** [hasadna/anyway#49]
I can think of nice icons for weather. but there is much more, and we should try to present as much as possible in a nice and visual way.

This assignment is for Dror.

**Comment by danielhers** [comment]
@tedwin007 I took your changes and updated them. You can find the latest version in my branch https://github.com/danielhers/anyway/tree/popup and continue from there.
We didn't merge it in yet because in order to be better than what we currently have, we need:
- The accident type to show in the subtitle
- The road type to show in the road state part
- The empty section (more info) to be hidden

**Comment by danielhers** [comment]
@tedwin007 can continue this now that #192 is completed and the fields are separate.

**Comment by galraij** [comment]
can we incorporate this in the pop-up?
https://jqueryui.com/accordion/#fillspace
This will save space and make it much more user friendly!

**Comment by omerxx** [comment]
@LironRS I think after @OmerSchechter's design you can push your last graphic improvement and then we ca close this

**Comment by danielhers** [comment]
@galraij should we close this?

**Comment by galraij** [comment]
if @OmerSchechter and @LironRS are happy, yes.
