### ISSUE TITLE
Add a color to the currently red circle on the low resolution map

### ISSUE THREAD

**Issue by simonaho** [hasadna/anyway#530]
Add a color according to the highest severity accident to the currently red circle on the low resolution map.
![image](https://cloud.githubusercontent.com/assets/16196934/12038313/b3b7208e-ae5f-11e5-8ee7-6e7a0898ba13.png)

**Comment by omerxx** [comment]
I think having the clusters colored is a bit pointless since from a certain level all clusters would statistically contain lethal accidents.
Beyond that, we would have a messy workspace with many colors, as we used to have back when clusters were part of our FE, contradicting our aim for a clean simple UI..
After removing cluster colors and consulting with @galraij we've decided to have distinct levels of border thickness to indicate the amount of accidents visually.

**Comment by simonaho** [comment]
Thank you for your comment. I agree with you that UI should be clean, and that at high resolution all circles will be red.
Still an important criteria is  that the view will be informative and will improve the data access.
For example if you look at obudget.org.il you can see that they have colorful circles, where blue represents budget shrinking, and red represents budget enlargement.
IMO the same concept can be used for ANYWAY, to allow high level view of dangerous places.
From my perspective the obudget UI looks quite clean, maybe we can use a similar method with circle sizes and colors, but without numbers.
Let's try to talk to a UX expert on Monday and see what she thinks.

**Comment by omerxx** [comment]
@simonaho, obudget are using a "clean canvas" background while we present our data on a map.
As I recall a UX professional had advised that we use as few layers and colors as possible since our canvas is a live map (As we zoom out more map details have to be valued, together with clustering).
I completely agree that we should be informative, but IMHO this particular point is where over-descriptive interface comes on top of a clean view. Numbers here play a great role of highlighting danger zones while allowing our user to understand the map and stay focused.
Large shapes like obudget use may do the opposite for us since our background is our core utility.

Hearing another expert's opinion is a good idea, let's do that.

**Comment by simonaho** [comment]
I thought about this a little bit more. I'm not a UX expert and I don't attempt to suggest a UX solution.
However, as I see it, a good UX is consistent an accurate. The current solution where in the high resolution the red color represents severe accident, while in the lower resolution the red color does not neceserally mean that there was a severe accident, is not a consistent solution.
Currently the same color means different things in different resolutions. 
So lets talk to a UX person and ask for a consistent solution (and clean and informative an impressive).

**Comment by simonaho** [comment]
duplicate of #368
