### ISSUE TITLE
Improve appearance of login modal

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#552]
Consult a UX person to design it properly.

**Comment by siv123456** [comment]
so this is what Lihi designed:

![login modal design from lihi](https://cloud.githubusercontent.com/assets/10827288/14262190/d965b968-fabc-11e5-9bb8-58ac99347a85.png)

this is where my implementation stands:

![login modal current status](https://cloud.githubusercontent.com/assets/10827288/14262255/4578307c-fabd-11e5-8c1c-2408d94e84f9.png)

i need some help/tips :
1.  how do i change the google button to google+ button ?
2. adding the maximize/minimize buttons in the modals header next to the "x" button. i guess its bootstrap/backbone involved but i couldn't find any helping implementation on the web ( i never used bootstrap nor backbone so i need something to work with :) ).

will be glad if anyone can help.
Thanks

**Comment by danielhers** [comment]
First of all, I think these are already better and I would be happy to
merge them if you create a pull request
Second, Google provide their own button and encourage you to use it:
https://developers.google.com/identity/branding-guidelines#g+signin-social-scopes
So does Facebook:
https://developers.facebook.com/docs/facebook-login/best-practices
Third, I don't think the maximize button is really necessary.
Thanks

**Comment by siv123456** [comment]
no problem , i'll create a pull request ,hopefully today.
will try updating the buttons first.
and i'm with you on the maximize button :)

**Comment by siv123456** [comment]
did we have google signin or facebook signin button working ?
because their not working in my local site.
if i'm going to change google button to G+ , am I to go through the entire process of creating an app ID and everything described on google guidelines page ?

**Comment by danielhers** [comment]
They work on the production site, but since the setting is url specific
they don't work when running locally.

**Comment by siv123456** [comment]
ok after consulting Avi i understand that google and facebook login buttons are created using bootstrap and font-awesome so i went and added bootstrap CDN links to html and updated font-awesome css CDN link + a few small html/css additions and this is what i have now (not so different then what we have now):

![login module](https://cloud.githubusercontent.com/assets/10827288/14612753/89c24b3e-05a1-11e6-9cd2-02c05dea23a9.png)

a few things:
~~~~~~~~~~~
1. there is no G+ button when using the current social buttons source - how critical is it ?
2. we have local bootstrap files (css, javascript) in the project - i understand there are pros and cons for using CDN vs. local files ,what do we prefer ? local files makes loading faster and its important to us as long as the server is weak ? do we make changes (is that a good practice ) in bootstrap css file thus we need the local file ?
3. apart from the issue i can see with updating the css (mentioned above) -do i need to somehow test the entire site and see how my changes influence ?

**Comment by danielhers** [comment]
Looks good.
1. What do you mean about the G+ button? Google supply their own button.
2. I don't think there's a reason to use local files. If anything, using the CDN files will be faster.
3. You should test around the site after your changes to see it all works.

**Comment by siv123456** [comment]
ok , here is my final try using bootstrap ( did find it after all)

![screenshot from 2016-04-19 00 11 18](https://cloud.githubusercontent.com/assets/10827288/14620037/450300fc-05c3-11e6-9004-75f6485545ed.png)


since its my first time tempering with bootstrap there are some things i dont understand thus my questions. some reading is required :)

anyhow , i'm going to delete the bootstrap css, js, fonts local files.
go over the site to make sure i didnt ruin anything.
i also need to check that G+ sign in actually works since what i did is just change the button icon , what about functionality ? i guess i need to change the authorization code behind to enable google+ sign in? how do i go about doing that ? is it just changing the oauth module ?

**Comment by danielhers** [comment]
I believe Google authentication works already. Doesn't it?

**Comment by siv123456** [comment]
ok , here is my final try using bootstrap ( did find it after all)

![Uploading Screenshot from 2016-04-19 00:11:18.png…]()


since its my first time tempering with bootstrap there are some things i dont understand thus my questions. some reading is required :)

anyhow , i'm going to delete the bootstrap css, js, fonts local files.
go over the site to make sure i didnt ruin anything.
i also need to check that G+ sign in actually works since what i did is just change the button icon , what about functionality ? i guess i need to change the authorization code behind to enable google+ sign in? how do i go about doing that ? is it just changing the oauth module ?

**Comment by siv123456** [comment]
yes , Google authentication is working but isn't there a difference between Google and Google+account with regard to authentication ?

**Comment by danielhers** [comment]
Right.
We [currently use Google OAuth 2.0 authentication](https://github.com/hasadna/anyway/blob/dev/oauth.py#L78).
Here are [instructions for migration to Google+ Sign In](https://developers.google.com/+/web/api/rest/auth-migration#update-oauth-20-login-or-migrate-to-google-sign-in).
If you want you can try changing that in `oauth.py`, but I understand the difference is just access to more fields from the user's Google+ account, whereas we only use the name and email, which are also available with Google OAuth 2.0. Still, it will be nice if you can get it to work.
We already have the client ID and key set in our server.

**Comment by siv123456** [comment]
ok ,just one question that comes to mind before i start : how can i test it ? (authentication is not working in my local site )

**Comment by danielhers** [comment]
You can [deploy your code to your own Heroku](https://github.com/hasadna/anyway#heroku-deployment) and set the environment variables there.
Then you can test with the [OAuth 2.0 Playground](https://bshaffer.github.io/oauth2-server-php-docs/cookbook/google-playground/).

**Comment by siv123456** [comment]
great , thanks
