### ISSUE TITLE
Simplify README

### ISSUE THREAD

**Issue by danielhers** [hasadna/anyway#601]
The setup instructions in the README are quite long and complicated, and should be simplified.

**Comment by r-darwish** [comment]
I think that part of what makes the instructions long is that they specify generic steps for setting up the Python environment, such as using virtualenv and installing Python itself in Windows. There are also instructions for specific tools such as c9 or Pycharm. 

I think these steps are redundant. Developers should know the generic steps for setting up a Python development environment and their favorite editor on their computer, and the README should only contain the instructions which are specific for deploying Anyway. What do you think?

**Comment by simonaho** [comment]
Its tricky because we have different levels of developers, quite a few of them rather novice. Installing Python on Windows for example for people who already have Python 3 installed requires handling the Path and more annoying stuff.
Maybe we can think of a modular explanation something like: if you have Python 2 installed you can skip this section ect.

**Comment by danielhers** [comment]
I agree that for any given developer, most of the README is completely
redundant and just making it harder to find the relevant part to that
developer. Maybe we could have a wiki or separate documentation for less
experienced developers, with links to the relevant pages from the main
README, instead of putting it all in one document.

**Comment by simonaho** [comment]
Wiki sounds like a good idea, and is available on github, so, only left to implement :-)
