### ISSUE TITLE
Run pylint in Travis

### ISSUE THREAD

**Issue by r-darwish** [hasadna/anyway#690]
I ran pylint on the code and found numerous bad indentations and other bad conventions. In order to keep the code tidy I suggest creating a `.pylintrc` configuration for the project and run it in Travis. I can start making progress in this if my suggestion is accepted.

**Comment by simonaho** [comment]
Hi Roey, thank you for your contribution. I think it will be a good idea to discuss your suggestion a bit before you implement it, especially since we do not ha an automatic regression test to cover us after the modifications. We usually meet on Mondays after seven pm at Electra tower floor 34 in Tel Aviv, on Goole Camus. It will be great if you can attend, then we can discuss your suggestion, and other potential contribution. If it is inconvenient we can discuss online. Looking forward to meet you.

**Comment by danielhers** [comment]
We have some tests on Travis, but they are quite minimal and don't really
check interaction with the site at all. A contribution in that area would
be most welcome.

**Comment by r-darwish** [comment]
@simonaho thank you for the invitation but at the moment it will be more convinient for me to discuss it online.

May I suggest that we do this change incrementally? As you can see [here](https://github.com/r-darwish/anyway/commit/973198ec1951b81d1b333c648b38f2c70b333400), when Pylint is set to ignore warnings and conventions issues, it finds only 3 errors (which seem like real bugs). If this patch is merged now then all the following contributions will be checked for errors. In the future we can enable more warnings and make the appropriate fixes when you feel ready. What do you think?

I also think this will help with #643 because pylint will catch Python 3 compatibility errors when run with Python 3

**Comment by danielhers** [comment]
I agree these corrections are valid, and it will certainly be helpful to find and correct more problems, as long as careful testing is done to avoid breaking the site. Integration testing is currently manual, but again, contributions are welcome.
Please open a PR and we'll merge. Thanks!

**Comment by moshe742** [comment]
I think Roey suggestion (both the first and the second) are good.
I don't like it that everything is not PEP 8 since I got used to it and it
is a good practice on python at least.

We can start by using a linter on with our ide and work as it tells us, se
just need to start using one.

The biggest problem I see is that on git we will see a change anywhere
there was a change, even if it was only an indentation change or something
like it.

Thus, I suggest to make the linting change in another commit if we do one,
that way it will be easier for the reviewer to check the changes.

BTW, can I change the files I work on to be PEP 8 compatible? I mean is it
OK with you?

On Wed, Aug 30, 2017 at 9:11 AM, Roey Darwish Dror <notifications@github.com

**Comment by r-darwish** [comment]
@danielhers I'll test my changes manually and then open a pull request. Thanks.

**Comment by danielhers** [comment]
@moshe742 of course, improving code quality is always welcome if done carefully. Don't worry so much about git. It's always possible to see what was the last change before a particular commit.
